#redis设置
spring:
  redis:
    host: 192.168.5.129
    port: 6379
    database: 0
    timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest  

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 服务器端口
server:
  port: 8781


#设置feign连接超时时间和响应时间
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    enabled: true
