#服务端口号
server:
  port: 8771
  
#sleuth采集量 默认0.1  
spring:
  sleuth:
    sampler:
      probability: 1  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
      
env: dev123123
